"""
run_robot.py  —  single-robot driver (no Vicon)
===================================================================
Set ROBOT_ID below to pick which robot to drive, then run this file.

Pure odometry: no pose correction, no Vicon dependency, no shell
launcher needed. Wrap waypoints are followed with navigate_to, same
as the move waypoints (no arc mode).

Runtime inputs (regenerated by compute_path.py / the website):
  - path_<ROBOT_ID>_robot.csv   waypoints in the robot's local frame
  - run_config_<ROBOT_ID>.json  direction, light color, etc.
"""

from irobot_edu_sdk.backend.bluetooth import Bluetooth
from irobot_edu_sdk.robots import event, Create3
import asyncio, csv, json, os

# ==================================================================
# ROBOT SELECTION
# ==================================================================
# Edit the default below to switch between A and B for manual runs;
# the website's robot agent overrides this with the ROBOT_ID env var.
ROBOT_ID = os.environ.get("ROBOT_ID", "A")

# ==================================================================
# LOADERS
# ==================================================================

_HERE = os.path.dirname(os.path.abspath(__file__))
ROBOT_INFO_DIR = os.path.join(_HERE, "robot_info")

def load_run_config(rid):
    """Read robot_info/run_config_<rid>.json."""
    with open(os.path.join(ROBOT_INFO_DIR, "run_config_" + rid + ".json")) as f:
        cfg = json.load(f)
    cfg["light_rgb"] = tuple(cfg["light_rgb"])
    if not cfg.get("bluetooth_address"):
        raise SystemExit(
            "Robot " + rid + " has no bluetooth_address in run_config_" + rid +
            ".json. Run `python setup_robots.py` to pair the robots first."
        )
    return cfg

def load_path(csv_name):
    """Read robot_info/path_<rid>_robot.csv (local frame) into a list of dicts."""
    pts = []
    with open(os.path.join(ROBOT_INFO_DIR, csv_name), newline="") as f:
        for row in csv.DictReader(f):
            pts.append({
                "x":       float(row["x"]),
                "y":       float(row["y"]),
                "type":    row["type"],
                "pole":    int(row["pole"]),
                "arc_deg": float(row["arc_deg"]),
            })
    return pts

# Loaded at module import so the rest of the file can read them
CFG  = load_run_config(ROBOT_ID)
PATH = load_path(CFG["path_csv"])

# ==================================================================
# ROBOT DRIVER
# ==================================================================

robot = Create3(Bluetooth(address=CFG["bluetooth_address"]))


@event(robot.when_play)
async def play(robot):
    await robot.reset_navigation()
    await robot.set_lights_on_rgb(*CFG["light_rgb"])   # color per run_config

    print("Robot " + CFG["rid"] +
          " | dir=" + CFG["dir"] +
          " | " + str(len(PATH)) + " waypoints")

    on_color = CFG["light_rgb"]

    current_pole = None

    for i, pt in enumerate(PATH):
        if pt["type"] == "start":
            continue

        if pt["type"] == "move":
            if pt["pole"] != current_pole:
                current_pole = pt["pole"]
                print("\n--- Heading to Pole " + str(current_pole) + " ---")
            await robot.navigate_to(pt["x"], pt["y"])

        elif pt["type"] == "wrap":

            prev = PATH[i - 1] if i > 0 else None

            is_first_wrap = (prev is None or prev["type"] != "wrap"
                             or prev["pole"] != pt["pole"])

            if is_first_wrap:
                await robot.set_lights_spin_rgb(255, 115, 0)
                print("  Wrapping pole " + str(pt["pole"]) +
                      " (" + CFG["dir"] + ")")

            await robot.navigate_to(pt["x"], pt["y"])

            nxt = PATH[i + 1] if i + 1 < len(PATH) else None
            is_last_wrap = (nxt is None or nxt["type"] != "wrap"
                            or nxt["pole"] != pt["pole"])
            if is_last_wrap:
                await robot.set_lights_on_rgb(*on_color)
                print("  Done wrapping pole " + str(pt["pole"]))

    await robot.set_lights_blink_rgb(255, 255, 255)
    await robot.play_note(440, 0.5)
    await robot.play_note(880, 0.5)
    await robot.stop_sound()
    print("\nRobot " + CFG["rid"] + " complete!")

    # Break out of the SDK's run_forever() so the process exits with
    # code 0. The agent treats that as "done"; without it robot.play()
    # would block forever after the robot finishes its path.
    loop = asyncio.get_event_loop()
    loop.call_later(0.5, loop.stop)

robot.play()
