"""
run_robot.py  —  hand-maintained driver (NOT auto-generated)
===================================================================
Set ROBOT_ID below, then launch via ./run_robot.sh (macOS: that sets
DYLD_LIBRARY_PATH so the Vicon dylibs load).

Runtime inputs:
  - path_<ROBOT_ID>_robot.csv   waypoints in the robot's local frame
                                (regenerated by compute_path.py / the website)
  - run_config_<ROBOT_ID>.json  per-robot constants
                                (regenerated by compute_path.py / the website)
  - vicon_config.json           Vicon host + subject names
                                (hand-maintained, NOT regenerated)

Toggles (edit here):
  - WRAP_MODE    "arc" | "navigate"
  - USE_VICON    True  -> between-wrap pose correction from Vicon
  - MOCK_ROBOT   True  -> simulate the Create3 with mock_robot.MockCreate3
                          (no Bluetooth, no Vicon SDK needed)

Correction strategy (Phase B):
  Before the first wrap of a pole AND after the last wrap of a pole,
  read Vicon, compare to the expected waypoint, and if off by more than
  the threshold, issue turn_* + move to close the gap, then a final turn
  to align heading with the next leg. No correction on intermediate
  wrap waypoints.
"""

import csv, json, math, os, time

# ==================================================================
# ROBOT SELECTION / MODE  (edit these)
# ==================================================================
ROBOT_ID   = "A"
WRAP_MODE  = "arc"         # "arc" | "navigate"
USE_VICON  = True         # False -> skip all Vicon reads + corrections
MOCK_ROBOT = True         # True  -> MockCreate3 instead of real Bluetooth Create3

# ==================================================================
# CONDITIONAL IMPORTS (Bluetooth/Create3 vs mock)
# ==================================================================
if MOCK_ROBOT:
    from mock_robot import MockCreate3, event
    Bluetooth = None
    _RealCreate3 = None
else:
    from irobot_edu_sdk.backend.bluetooth import Bluetooth
    from irobot_edu_sdk.robots import event, Create3 as _RealCreate3
    MockCreate3 = None

# ==================================================================
# LOADERS
# ==================================================================
_HERE = os.path.dirname(os.path.abspath(__file__))

def load_run_config(rid):
    with open(os.path.join(_HERE, "run_config_" + rid + ".json")) as f:
        cfg = json.load(f)
    cfg["light_rgb"] = tuple(cfg["light_rgb"])
    return cfg

def load_path(csv_name):
    pts = []
    with open(os.path.join(_HERE, csv_name), newline="") as f:
        for row in csv.DictReader(f):
            pts.append({
                "x":       float(row["x"]),
                "y":       float(row["y"]),
                "type":    row["type"],
                "pole":    int(row["pole"]),
                "arc_deg": float(row["arc_deg"]),
            })
    return pts

def load_vicon_config():
    path = os.path.join(_HERE, "vicon_config.json")
    if not os.path.exists(path):
        raise FileNotFoundError(
            "vicon_config.json not found — required when USE_VICON=True. "
            "Create it with host + subjects, or set USE_VICON=False."
        )
    with open(path) as f:
        return json.load(f)

CFG  = load_run_config(ROBOT_ID)
PATH = load_path(CFG["path_csv"])

# ==================================================================
# POSE SOURCES  (Vicon or mock-robot pose, in robot-local cm + deg)
# ==================================================================

def _yaw_from_quat(qx, qy, qz, qw):
    """Yaw (rotation around Z) in degrees, assuming Vicon Z is up."""
    siny_cosp = 2.0 * (qw * qz + qx * qy)
    cosy_cosp = 1.0 - 2.0 * (qy * qy + qz * qz)
    return math.degrees(math.atan2(siny_cosp, cosy_cosp))

def _wrap180(a):
    while a >  180.0: a -= 360.0
    while a <= -180.0: a += 360.0
    return a


class ViconPoseSource:
    """Reads from a running ViconClient and converts to the robot's
    local frame (cm, heading in degrees with 90° = forward, matching
    the SDK's reset_navigation grid)."""

    def __init__(self, client, subject, start_pos_mm, start_yaw_deg):
        self.client = client
        self.subject = subject
        self.sx_mm = float(start_pos_mm[0])
        self.sy_mm = float(start_pos_mm[1])
        self.start_yaw = float(start_yaw_deg)
        # Rotation to apply so that the robot's startup facing direction
        # ends up as the local +y axis (SDK heading = 90°).
        self.rot_deg = 90.0 - self.start_yaw
        self._rot_rad = math.radians(self.rot_deg)
        self._cos = math.cos(self._rot_rad)
        self._sin = math.sin(self._rot_rad)

    def get_pose_local(self):
        frame = self.client.latest_frame
        if frame is None:
            return None
        body = frame.subject(self.subject)
        if body is None or body.occluded:
            return None
        dx_mm = float(body.position[0]) - self.sx_mm
        dy_mm = float(body.position[1]) - self.sy_mm
        x_local_mm = self._cos * dx_mm - self._sin * dy_mm
        y_local_mm = self._sin * dx_mm + self._cos * dy_mm
        qx, qy, qz, qw = body.rotation_quat
        yaw = _yaw_from_quat(qx, qy, qz, qw)
        h_local = _wrap180(yaw + self.rot_deg)
        return (x_local_mm / 10.0, y_local_mm / 10.0, h_local)


class MockPoseSource:
    """Returns the mock robot's own simulated pose — perfect tracking.
    (MockCreate3 already uses SDK convention: reset -> heading 90°.)"""

    def __init__(self, mock_robot):
        self._mock = mock_robot

    def get_pose_local(self):
        return (self._mock.x, self._mock.y, self._mock.heading)


# ==================================================================
# ROBOT CONSTRUCTION
# ==================================================================
if MOCK_ROBOT:
    robot = MockCreate3()
else:
    robot = _RealCreate3(Bluetooth(address=CFG["bluetooth_address"]))


# ==================================================================
# BOOT-TIME VICON CLIENT  (real mode only; mock uses MockPoseSource)
# ==================================================================
_vicon_client = None
_vicon_subject = None
_vicon_threshold = 5.0

if USE_VICON and not MOCK_ROBOT:
    vcfg = load_vicon_config()
    _vicon_subject = vcfg["subjects"].get(ROBOT_ID)
    if not _vicon_subject:
        raise RuntimeError("vicon_config.json has no subject for ROBOT_ID=" + ROBOT_ID)
    _vicon_threshold = float(vcfg.get("correction_threshold_cm", 5.0))

    from vicon_sdk import ViconClient
    print("[vicon] connecting to " + vcfg["host"] +
          " | subject=" + _vicon_subject +
          " | threshold=" + str(_vicon_threshold) + " cm")
    _vicon_client = ViconClient(vcfg["host"])
    _vicon_client.start()

    # wait up to 5 s for the first frame
    deadline = time.time() + 5.0
    while _vicon_client.latest_frame is None and time.time() < deadline:
        time.sleep(0.05)
    if _vicon_client.latest_frame is None:
        _vicon_client.stop()
        raise RuntimeError("[vicon] no frames received within 5 s — check the server")
    print("[vicon] connected, first frame received.")
elif USE_VICON and MOCK_ROBOT:
    print("[vicon] mock mode — using MockPoseSource (perfect tracking)")
elif not USE_VICON:
    print("[vicon] disabled (USE_VICON=False) — running pure odometry")


# ==================================================================
# CORRECTION HELPER  (relative turn + move, no navigate_to)
# ==================================================================

async def correct_pose(robot, pose_src, label, pt, next_pt, threshold_cm):
    """If Vicon says we're > threshold off expected (pt.x, pt.y), turn
    to face the expected spot and drive there. Then, if next_pt is
    given, turn once more to face the next leg.

    Prints useful location info before and after.
    """
    if pose_src is None:
        return

    actual = pose_src.get_pose_local()
    if actual is None:
        print("  [correct " + label + "] no Vicon pose (occluded?) — skipping")
        return
    ax, ay, ah = actual
    ex, ey = pt["x"], pt["y"]
    dx, dy = ex - ax, ey - ay
    err = math.hypot(dx, dy)

    print("  [pose " + label + "] expected=(" + f"{ex:+.1f}, {ey:+.1f}" +
          ") vicon=(" + f"{ax:+.1f}, {ay:+.1f}, {ah:+.1f}°" +
          ") err=" + f"{err:.1f}" + " cm")

    if err > threshold_cm:
        target_dir = math.degrees(math.atan2(dy, dx))
        turn_delta = _wrap180(target_dir - ah)
        print("  [correct " + label + "] turn " + f"{turn_delta:+.1f}°" +
              " then move " + f"{err:.1f}" + " cm")
        if abs(turn_delta) > 0.5:
            if turn_delta >= 0:
                await robot.turn_left(turn_delta)
            else:
                await robot.turn_right(-turn_delta)
        await robot.move(err)
        ah = target_dir  # best estimate of heading after the move

        # Log post-correction pose
        post = pose_src.get_pose_local()
        if post is not None:
            px, py, ph = post
            perr = math.hypot(ex - px, ey - py)
            print("  [pose " + label + " post] vicon=(" +
                  f"{px:+.1f}, {py:+.1f}, {ph:+.1f}°" +
                  ") residual=" + f"{perr:.1f}" + " cm")
            ax, ay, ah = px, py, ph
    else:
        print("  [correct " + label + "] within threshold (" +
              f"{threshold_cm:.1f}" + " cm) — no move")

    # Optional heading alignment for the next leg
    if next_pt is not None:
        desired = math.degrees(math.atan2(next_pt["y"] - ey, next_pt["x"] - ex))
        final_turn = _wrap180(desired - ah)
        if abs(final_turn) > 0.5:
            print("  [correct " + label + "] align heading " +
                  f"{final_turn:+.1f}°" + " toward next leg")
            if final_turn >= 0:
                await robot.turn_left(final_turn)
            else:
                await robot.turn_right(-final_turn)


# ==================================================================
# MAIN EVENT
# ==================================================================

@event(robot.when_play)
async def play(robot):
    await robot.reset_navigation()
    await robot.set_lights_on_rgb(*CFG["light_rgb"])

    # ---- Build pose source (after reset_navigation so Vicon start is correct) ----
    pose_src = None
    if USE_VICON:
        if MOCK_ROBOT:
            pose_src = MockPoseSource(robot)
        else:
            frame = _vicon_client.latest_frame
            body = frame.subject(_vicon_subject) if frame is not None else None
            if body is None or body.occluded:
                print("[vicon] ERROR: subject '" + _vicon_subject +
                      "' not visible at startup — continuing without correction")
            else:
                start_pos_mm = (float(body.position[0]), float(body.position[1]))
                start_yaw = _yaw_from_quat(*body.rotation_quat)
                pose_src = ViconPoseSource(_vicon_client, _vicon_subject,
                                           start_pos_mm, start_yaw)
                print("[vicon] start calibration: " +
                      "vicon_world=(" + f"{start_pos_mm[0]:+.1f}, {start_pos_mm[1]:+.1f}" +
                      ") mm | yaw=" + f"{start_yaw:+.1f}°")
                p0 = pose_src.get_pose_local()
                if p0:
                    print("[vicon] local frame check at startup: " +
                          "(" + f"{p0[0]:+.2f}, {p0[1]:+.2f}, {p0[2]:+.1f}°" +
                          ") — should be near (0, 0, 90°)")

    print("Robot " + CFG["rid"] +
          " | dir=" + CFG["dir"] +
          " | wrap=" + WRAP_MODE +
          " | vicon=" + ("on" if pose_src else "off") +
          " | " + str(len(PATH)) + " waypoints")

    arc_method = getattr(robot, CFG["arc_cmd"])
    arc_r      = CFG["arc_r"]
    on_color   = CFG["light_rgb"]

    current_pole = None

    for i, pt in enumerate(PATH):
        if pt["type"] == "start":
            continue

        next_pt = PATH[i + 1] if i + 1 < len(PATH) else None

        if pt["type"] == "move":
            if pt["pole"] != current_pole:
                current_pole = pt["pole"]
                print("\n--- Heading to Pole " + str(current_pole) + " ---")
            await robot.navigate_to(pt["x"], pt["y"])

        elif pt["type"] == "wrap":

            prev = PATH[i - 1] if i > 0 else None

            is_first_wrap = (prev is None or prev["type"] != "wrap"
                             or prev["pole"] != pt["pole"])

            # ARC MODE
            if WRAP_MODE == "arc":
                if is_first_wrap:
                    # Find the LAST wrap point of this pole — that's where
                    # the arc command leaves us (arc exit tangent).
                    j = i
                    while (j + 1 < len(PATH)
                           and PATH[j + 1]["type"] == "wrap"
                           and PATH[j + 1]["pole"] == pt["pole"]):
                        j += 1
                    exit_pt   = PATH[j]
                    exit_next = PATH[j + 1] if j + 1 < len(PATH) else None

                    # Phase-B correction: fix pose BEFORE the arc so the
                    # circle lands on the pole. Align heading with the
                    # arc tangent (direction of the next wrap waypoint).
                    await correct_pose(
                        robot, pose_src,
                        "pole " + str(pt["pole"]) + " pre-wrap",
                        pt, next_pt, _vicon_threshold,
                    )

                    await robot.set_lights_spin_rgb(255, 115, 0)
                    sweep = pt.get("arc_deg", 360)
                    print("  Wrapping pole " + str(pt["pole"]) +
                          " (" + CFG["dir"] + ") [arc mode, " +
                          str(round(sweep, 1)) + " deg]")
                    await arc_method(sweep, arc_r)
                    await robot.set_lights_on_rgb(*on_color)
                    print("  Done wrapping pole " + str(pt["pole"]))

                    # Phase-B correction: fix pose AFTER the arc so the
                    # transit to the next pole starts clean. Expected
                    # position is the arc EXIT (last wrap point of this
                    # pole), and the next leg is the transit move.
                    await correct_pose(
                        robot, pose_src,
                        "pole " + str(pt["pole"]) + " post-wrap",
                        exit_pt, exit_next, _vicon_threshold,
                    )
                continue

            # NAVIGATE MODE
            elif WRAP_MODE == "navigate":
                if is_first_wrap:
                    await correct_pose(
                        robot, pose_src,
                        "pole " + str(pt["pole"]) + " pre-wrap",
                        pt, next_pt, _vicon_threshold,
                    )
                    await robot.set_lights_spin_rgb(255, 115, 0)
                    print("  Wrapping pole " + str(pt["pole"]) +
                          " (" + CFG["dir"] + ") [navigate mode]")

                await robot.navigate_to(pt["x"], pt["y"])

                nxt = PATH[i + 1] if i + 1 < len(PATH) else None
                is_last_wrap = (nxt is None or nxt["type"] != "wrap"
                                or nxt["pole"] != pt["pole"])
                if is_last_wrap:
                    await robot.set_lights_on_rgb(*on_color)
                    print("  Done wrapping pole " + str(pt["pole"]))
                    await correct_pose(
                        robot, pose_src,
                        "pole " + str(pt["pole"]) + " post-wrap",
                        pt, next_pt, _vicon_threshold,
                    )

    # Finale
    if pose_src is not None:
        final = pose_src.get_pose_local()
        if final is not None:
            print("[vicon] final pose: (" +
                  f"{final[0]:+.1f}, {final[1]:+.1f}, {final[2]:+.1f}°" + ")")

    await robot.set_lights_blink_rgb(255, 255, 255)
    await robot.play_note(440, 0.5)
    await robot.play_note(880, 0.5)
    await robot.stop_sound()
    print("\nRobot " + CFG["rid"] + " complete!")


# ==================================================================
# RUN  (with Vicon teardown on exit)
# ==================================================================
try:
    robot.play()
finally:
    if _vicon_client is not None:
        _vicon_client.stop()
