"""
run_robot_noVicon.py  —  no-Vicon driver (snapshot of commit 9939c21)
===================================================================
Set ROBOT_ID below to pick which robot to drive, then run this file.

This is the pre-Vicon version of the driver: pure odometry, no pose
correction, no Vicon dependency, no shell launcher needed. Kept as a
known-good baseline. For the Vicon-corrected version see run_robot.py.

Runtime inputs (regenerated by compute_path.py / the website):
  - path_<ROBOT_ID>_robot.csv   waypoints in the robot's local frame
  - run_config_<ROBOT_ID>.json  direction, ARC_R, light color, etc.

Tuning knob that lives here (edit directly):
  - WRAP_MODE   "arc" | "navigate"
"""

from irobot_edu_sdk.backend.bluetooth import Bluetooth
from irobot_edu_sdk.robots import event, Create3
import csv, json, os

# ==================================================================
# ROBOT SELECTION  (edit this line to switch between A and B)
# ==================================================================
ROBOT_ID = "A"

# ==================================================================
# WRAP MODE - how to draw the circle around the pole
# Comment out one, leave the other active.
# ==================================================================
WRAP_MODE = "arc"
# WRAP_MODE = "navigate"

# ==================================================================
# LOADERS
# ==================================================================

_HERE = os.path.dirname(os.path.abspath(__file__))

def load_run_config(rid):
    """Read run_config_<rid>.json."""
    with open(os.path.join(_HERE, "run_config_" + rid + ".json")) as f:
        cfg = json.load(f)
    cfg["light_rgb"] = tuple(cfg["light_rgb"])
    return cfg

def load_path(csv_name):
    """Read path_<rid>_robot.csv (local frame) into a list of dicts."""
    pts = []
    with open(os.path.join(_HERE, csv_name), newline="") as f:
        for row in csv.DictReader(f):
            pts.append({
                "x":       float(row["x"]),
                "y":       float(row["y"]),
                "type":    row["type"],
                "pole":    int(row["pole"]),
                "arc_deg": float(row["arc_deg"]),
            })
    return pts

# Loaded at module import so the rest of the file can read them
CFG  = load_run_config(ROBOT_ID)
PATH = load_path(CFG["path_csv"])

# ==================================================================
# ROBOT DRIVER
# ==================================================================

robot = Create3(Bluetooth(address=CFG["bluetooth_address"]))


@event(robot.when_play)
async def play(robot):
    await robot.reset_navigation()
    await robot.set_lights_on_rgb(*CFG["light_rgb"])   # color per run_config

    print("Robot " + CFG["rid"] +
          " | dir=" + CFG["dir"] +
          " | wrap=" + WRAP_MODE +
          " | " + str(len(PATH)) + " waypoints")

    arc_method = getattr(robot, CFG["arc_cmd"])   # arc_left or arc_right
    arc_r      = CFG["arc_r"]
    on_color   = CFG["light_rgb"]

    current_pole = None

    for i, pt in enumerate(PATH):
        if pt["type"] == "start":
            continue

        if pt["type"] == "move":
            if pt["pole"] != current_pole:
                current_pole = pt["pole"]
                print("\n--- Heading to Pole " + str(current_pole) + " ---")
            await robot.navigate_to(pt["x"], pt["y"])

        elif pt["type"] == "wrap":

            prev = PATH[i - 1] if i > 0 else None

            is_first_wrap = (prev is None or prev["type"] != "wrap"
                             or prev["pole"] != pt["pole"])

            # ARC MODE - one big arc on the first wrap point, skip the rest.
            if WRAP_MODE == "arc":
                if is_first_wrap:
                    await robot.set_lights_spin_rgb(255, 115, 0)
                    sweep = pt.get("arc_deg", 360)
                    print("  Wrapping pole " + str(pt["pole"]) +
                          " (" + CFG["dir"] + ") [arc mode, " +
                          str(round(sweep, 1)) + " deg]")
                    await arc_method(sweep, arc_r)
                    await robot.set_lights_on_rgb(*on_color)
                    print("  Done wrapping pole " + str(pt["pole"]))
                continue

            # NAVIGATE MODE - drive from wrap point to wrap point.
            elif WRAP_MODE == "navigate":
                if is_first_wrap:
                    await robot.set_lights_spin_rgb(255, 115, 0)
                    print("  Wrapping pole " + str(pt["pole"]) +
                          " (" + CFG["dir"] + ") [navigate mode]")

                await robot.navigate_to(pt["x"], pt["y"])

                nxt = PATH[i + 1] if i + 1 < len(PATH) else None
                is_last_wrap = (nxt is None or nxt["type"] != "wrap"
                                or nxt["pole"] != pt["pole"])
                if is_last_wrap:
                    await robot.set_lights_on_rgb(*on_color)
                    print("  Done wrapping pole " + str(pt["pole"]))

    await robot.set_lights_blink_rgb(255, 255, 255)
    await robot.play_note(440, 0.5)
    await robot.play_note(880, 0.5)
    await robot.stop_sound()
    print("\nRobot " + CFG["rid"] + " complete!")

robot.play()
